### ISSUE TITLE
[Question]: Is there a way to set MVStore configuration manually?

### ISSUE THREAD

**Issue by stdStudent** [nitrite/nitrite-java#1072]
There's a [bug](https://github.com/h2database/h2database/issues/4048) in MVStore that I've been encountering. Basically, sometimes internal assertion fails:
```java
Caused by: java.lang.AssertionError: 95203328 != 65208320
    at org.h2.mvstore.RandomAccessStore.shrinkStoreIfPossible(RandomAccessStore.java:679)
```

People suggest to set `AUTO_COMPACT_FILL_RATE=0` to a database configuration. Is that possible? 

Please, notice that I do not activate compression in my MVStoreModule configuration.

**Comment by anidotnet** [comment]
These are the available configurations for H2 mvstore - https://nitrite.dizitart.com/java-sdk/modules/store-modules/mvstore/index.html

**Comment by anidotnet** [comment]
I was not in front of my machine so could not dig deep. The settings you are talking is already disabled in nitrite mvstore - https://github.com/nitrite/nitrite-java/blob/80f96547266e289ed87312103181c693e201f3f2/nitrite-mvstore-adapter/src/main/java/org/dizitart/no2/mvstore/MVStoreUtils.java#L131

The root cause for the h2 bug could be something else.

**Comment by stdStudent** [comment]
I see. This issue is indeed hard to reproduce, I hope it gets fixed soon. Anyway, thank you, @anidotnet!
