### ISSUE TITLE
Better synchronisation handle

### ISSUE THREAD

**Issue by anidotnet** [nitrite/nitrite-java#189]
Put all read write operations inside `ReadWriteOperation.java` using read write lock.

**Comment by sheinbergon** [comment]
Question: Wouldn't it be preferable to use built-in MVStore transactions instead? I have a feeling it could provide better performance. Also, this feature should supporting opting out (or opting-in) because it'll come at the cost of performance for those of measuring operation latency in microseconds, and do not require concurrent access.

**Comment by anidotnet** [comment]
I tried to use their Transaction store earlier, but according to them it is not meant for public consumption. Here are the comments - https://github.com/h2database/h2database/issues/1324#issuecomment-422873631

**Comment by anidotnet** [comment]
Having said above, when I see their [TestTransactionStore](https://github.com/h2database/h2database/blob/master/h2/src/test/org/h2/test/store/TestTransactionStore.java) I think they have some well defined api which can be used outside of h2 database boundary. When I get some time from my day job, I have to do some analysis to see if it is compatible with nitrite's api.

If you can spend sometime, you can help in the analysis. For that you have to look at **feature-spatial** branch where all v4.x work is. This branch has breaking changes.

**Comment by anidotnet** [comment]
Introduced `ReentrantReadWriteLock` as part of fix for #193 .

**Comment by anidotnet** [comment]
Handled in 4.x branch and is available in 4.0.0-SNAPSHOTS
