### ISSUE TITLE
Cannot retrieve data from datastore with second process

### ISSUE THREAD

**Issue by drgb88** [nitrite/nitrite-java#250]
I ran one small project to create a file-based DB and save some data to it. Then I made a small Spring Boot project to use the same DB, but this will only retrieve data that it, the second project, stores in the DB. The data stored in the DB by the first project is not available, yields empty cursor. The DB is not open in the first project. Everything seems to be committed. Is this a bug, or what do I do to get the previous data from the file?

**Comment by anidotnet** [comment]
This is very strange and unheard of. Anyway, could you please add unique serialVersionUID in your data classes and try? If that does not help, could you provide some reproducible code?

**Comment by anidotnet** [comment]
Any update on this yet? Make sure the db is not opened from 2 applications simultaneously. There is a lock on the database file, if it is opened in one java process, it can't be opened from another java process, unless the first java process is closed.

**Comment by drgb88** [comment]
Anindya:
I did add  a unique serialVersionUID to the two data classes, but this had
no effect.
I am attaching a zip of the two projects. The Nitrite DB was created with
ProtoBlog2, then I made ProtoBlog3 to use Spring Boot with the Nitrite DB.
All of these technologies are new to me so excuse the code mess. My idea
was to create a simple blog using a completely new stack.
But even just the Users data class which is very simple: I can add users
with protoBlog2 and then retrieve those Users, I can create users with
ProtoBlog3 and then retrieve those users with ProtoBlog3.
There is probably something basic and stupid that is causing this. But only
one application was attempting to use the Nitrite DB at one time. Both apps
used the same JVM version.
Anyway, have a look it you like, and I will keep fiddling with it. I had to
delete a number of gradle scripts to allow the zip file to be attached to
this email.

Many Thanks,

Geoffrey Bays

**Comment by anidotnet** [comment]
Hi @drgb88 unfortunately the attachment has not been uploaded to github. You need add those here from github issue.

**Comment by drgb88** [comment]
Here are the files. minus scripts and libraries.
Look at the NitriteHandler class and the User and Post classes in both projects. I have included the Nitrite DB as well.
[ProtoBlog2And3.zip](https://github.com/nitrite/nitrite-java/files/5185435/ProtoBlog2And3.zip)

**Comment by anidotnet** [comment]
You are facing this issue is because, the fully qualified class name of Post is different in 2 different projects

ProtoBlog2 - proto.proto.Proto
ProtoBlog3 - ipso.proto.protoblog3.model.Proto

For an object repository, nitrite creates one underlying collection with name = fqn of the class + key (if any). Here in your case, basically you are writing data in one collection and reading it from another collection.

If you open the db file in nitrite-explorer, you will see what I am talking about. Fix the package name, and you will have no problems.

![image](https://user-images.githubusercontent.com/696662/94148097-ceb77a80-fe93-11ea-9970-d69d96441b5d.png)

![image](https://user-images.githubusercontent.com/696662/94148170-e7279500-fe93-11ea-8eee-44ab7744ecfe.png)

**Comment by drgb88** [comment]
Thank you for your explanation. I suspected this issue was related to the
basic functioning of Nitrite that differs from a standard RDBMS.
I will get a copy of Nitrite Explorer and that will clarify anything else
perplexing that may arise

Thanks Again,

Geoffrey Bays
