### ISSUE TITLE
Database file size grows exponentially if attributes indexed before adding elements, dropIndex does not restore small size

### ISSUE THREAD

**Issue by tkainrad** [nitrite/nitrite-java#295]
It appears that the database file size grows exponentially if we call `createIndex` on our fields before we add the actual data.
E.g. a database file that has ~300MB if indexes are created at the end suddenly has 1.2GB if the indexes are created in the beginning. For even larger data sets, this can quickly become troublesome.

Dropping the indexes does not recover the small file size. `rebuildIndex` does not help either. So, it seems to me that I have no way of reducing the database file size again.

It seems to be reproducible with any kind of data. Larger data sets (10k+ documents) make the problem more obvious.

Is there any way to change the indexing so that it doesn't matter for the file size whether the indexes are created before adding the data? If not, can `dropIndex` be fixed so that it fully deletes all space that was occupied by the index?

Thank you very much for looking at this!

**Comment by tkainrad** [comment]
Thank you for the quick response!

I did try compacting, even though I didn't know that it wasn't on by default. Doesn't seem to have an effect on the size though in my examples.

I will try out the snapshot builds and get back to you, thanks!

**Comment by anidotnet** [comment]
I have just added mapdb storage adapter support in 4.x snapshot. You can try that one also.

**Comment by tkainrad** [comment]
I am excited to try these out and compare performance. However, due to the API changes, it is not so trivial to implement this with the current approach.  
It would be great if there was a way also in 3.x to drop an index so that all of its disk space is released.

**Comment by anidotnet** [comment]
It won't be possible for mvstore, as it stores version information. That's why even if you delete the data, the old version is still there in the db file and there is no api to delete/disable those.

There are some issues on mvstore regarding this

- https://groups.google.com/g/h2-database/c/YrYi0U-onmw
- https://github.com/h2database/h2database/issues/610
- https://github.com/h2database/h2database/issues/1670

There are 2 possible solutions are in my mind

1. Go to this [line](https://github.com/nitrite/nitrite-java/blob/cb8b2a1c39f8dfcbb425046f23ef9036b690ffdd/nitrite/src/main/java/org/dizitart/no2/NitriteBuilder.java#L504) and change the version to keep value = 0, build the jar and check if it improves your situation or not. After that I can give a fix for this.

2. If the above does not help, you can delete the old db file, and re-create a new one with fresh data and indexes, this will definitely decrease the size of the file.

**Comment by tkainrad** [comment]
Thank you for this detailed answer.

I followed your suggestion and built with `store.setVersionsToKeep(0);`. Unfortunately, it did not change anything. I suppose this is because `setVersionsToKeep` only works with in-memory stores: http://javadox.com/com.h2database/h2/1.4.191/org/h2/mvstore/MVStore.html#setVersionsToKeep(int)

I guess I will have to try to avoid indexing until all/most of the data is inserted and recreate into a new file if the disk size grows too large.

Do you have any performance estimates already for versions 4.X with _rocksdb_ and _mapdb_? Will it be slower in exchange for smaller file sizes or is it similarly fast or maybe even faster?

**Comment by anidotnet** [comment]
I have a jmh project setup to compare the performance benifit. Here is the project - https://github.com/nitrite/nitrite-jmh/

You can download jmh report from the build artifacts in action tab here - https://github.com/nitrite/nitrite-jmh/suites/1126559824/artifacts/16019090

You can also visualize the json report here - https://jmh.morethan.io/

4.x has higher throughput. But db size-wise rocksdb implementation is more stable when record size reaches to 1 million or more. Mapdb is not so promising, it is slower than mvstore and rocksdb.
