### ISSUE TITLE
add collection fields to text index

### ISSUE THREAD

**Issue by willie68** [nitrite/nitrite-java#45]
it would be nice, if a collection like List<String> or Map<String, String> can be added to the text index.

**Comment by anidotnet** [comment]
Can you clarify with an example?

**Comment by willie68** [comment]
Sorry, but i don't think, i can/will contribute that deep, because there are, for me personally, to many development dependencies in this project, that i don't like. Like lombok, gradle and so on. 
(Only for the development process not for the software itself!)

Back to the topic: 
I want to add an tagging solution to stored objects. This tags should be stored into a simple List<String>. 
And i want to search after all objects, with a specific tag added. It would be sufficient, that this fields will only showup in the fulltext index.
That's the use case behind this feature request.

**Comment by anidotnet** [comment]
OK. I'll try to implement it using multikey-index whenever I get some time. And it does require a lot of time (both for development and testing) as this will incur significant changes.

For your use case, instead of storing them into a list, you can save the tags as a delimited string and run full text indexing on it for the time being. The tokenizer will tokenize the string and will store each tag separately, which will have the same effect while searching. 

Once I implement array indexing, you can store them as a list.

**Comment by anidotnet** [comment]
The changes should be available to 4.0.0-SNAPSHOTS
