### ISSUE TITLE
Upgrade H2 database version

### ISSUE THREAD

**Issue by theodm** [nitrite/nitrite-java#720]
Hello,

I would like to propose an update to the underlying h2 database. Unfortunately, probably a migration plan will be needed.

Related: https://github.com/nitrite/nitrite-java/pull/712

**Comment by anidotnet** [comment]
Thanks for the interest, I'll work on it in 4.x branch, but unfortunately it won't be backward compatible. Database file created with nitrite 3.x won't be able to open with 4.x after this change. 

If you have any automated migration plan in mind that we can incorporate in nitrite so that user can seamlessly upgrade to 4.x (when released), I am all ears.

**NOTE** : I am moving this issue to discussion as it needs further deliberation.
