### ISSUE TITLE
nitriteMapper is null?

### ISSUE THREAD

**Issue by yonimoses** [nitrite/nitrite-java#808]
Hi,

Trying to work with nitrite 3.X, so far so good.
I'm mainly using the ObjectRepository, but I wanted to try querying nested docs using the getCollection and got  the 

`NitriteMapper.isValueType(Object)" because "nitriteMapper" is null` in 
`ValidationUtils.validateSearchTerm`

My actual code that causes that is : 
`nitrite.getCollection(Advisory.class.getName()).find(eq("advisory_details.summary", "Text To Match"))`

any suggestions?

**Comment by anidotnet** [comment]
You need to use ObjectRepository api instead of collection.

Try to use:

```java
ObjectRepository<Advisory> repository = nitrite.getRepository(Advisory.class);
Cursor<Advisory> cursor = repository.find(eq("advisory_details.summary", "Text To Match"));
```

`NitriteMapper` is used in `ObjectRepository` to map object to document and vice versa. In `NitriteCollection`, for obvious reason `NitriteMapper` is not set as it does not deal with objects directly. So mix and match of api is not advisable. If you are dealing with objects, you need to use `ObjectRepository` api, if you are dealing with only documents, use collection api.
